INSERT INTO consumer (consumer_id,
                        mobile,
                        pwd,
                        is_enable,
                        is_non_expire,
                        is_non_lock,
                        wechat_id,
                        qq_id,
                        weibo_id,
                        nickname,
                        head,
                        email,
                        sex,
                        roles,
                        pay_pwd,
                        reg_type,
                        source_head)
VALUES ('119d8c62b8b04154a073b3f6c3d9e14f',
        '18202837563',
        'e10adc3949ba59abbe56e057f20f883e',
        't',
        't',
        't',
        'ogIXq0HrDq3kS6MAHqMI1RUqBrGw',
        NULL,
        NULL,
        '18202837563',
        'head/6dc93e2e0809426ca8a9e6ede30b0b50.JPEG',
        NULL,
        '男',
        '[ROLE_CONSUMER, ROLE_LAYER]',
        NULL,
        'S',
        'https://wx.qlogo.cn/mmopen/vi_32/MftzC3yHluDbjZ9c3sYEibUuXNkC3pha8E6pibZO3Wh0Zop0bqHLcltjmrENc4R8Xm6oJECQGibAxZot1v9PR1hsw/132');
